### ISSUE TITLE
Discrepancy between different calc_detailed_topology methods

### ISSUE THREAD

**Issue by AliGhorashiCMT** [thchr/SymmetryBases.jl#1]
```jl
calc_detailed_topology([1, 2, 1, 0, 1, 0, 1, 1, 3], brs)
calc_detailed_topology([1, 2, 1, 0, 1, 0, 1, 1, 3], nontopologicalbasis, brs)
```

Give different answers (trivial vs fragile) for 

```jl
sb, brs = SymmetryBases.compatibility_basis(16, 2)
brsmat= matrix(brs, true)

F = smith(brsmat)
nontopologicalbasis = nontopological_basis(F, brs)​
```

Issue is apparently related to fragile bands adding up to give trivial bands

**Comment by thchr** [comment]
I don't think I ever got around to fixing this - I just had some internal comment that the method should not be used - so thanks for filing an issue for it; made me remember to do it now :).

Fixed in https://github.com/thchr/SymmetryBases.jl/commit/1e9289e3314065f203e89671c71b9277f476b207 by removing https://github.com/thchr/SymmetryBases.jl/blob/465bb899b484edf7185f3a595a55ccb9c8ccce82/src/symvec.jl#L112-L192.
